sys:
  auth:
    tokenHeaderName: auth-token
server:
  port: ${SERVER_PORT:6002}
spring:
  application:
    name: system
  web:
    allowedOriginPatterns:
      - http://localhost:**
      - http://demo.xhansky.cn/**
      - http://192.168.**
  datasource:
    first:
      url: jdbc:mysql://localhost:3306/bms?characterEncoding=utf-8
      username: root
      password: 123456
      configuration:
        maximum-pool-size: 20
    second:
      url: jdbc:postgresql://localhost:5432/bms
      username: postgres
      password: 123456
      configuration:
        maximum-pool-size: 20
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 20
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: true
xxl:
  job:
    admin:
      ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://122.51.118.42:8088/xxl-job-admin
    ### 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: default_token

minio:
  endpoint: http://122.51.118.42:9000
  access-key: QEGiz63wnKckxgmvTwre
  secret-key: CoWs7QBrFjsEonoFjkOx9eQhZGfE74n9VlmVNMOM
  bucket: bucket1
